apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    uid: Postgres
    url: postgres:5432
    user: breakwall
    secureJsonData:
      password: breakwall
    database: breakwall
    jsonData:
      sslmode: 'disable'
